Completed_task_string
FlyLikeSoarin/atp-cpp-semester-1 pull request #34
Opened 2021-11-09 17:59 UTC by vsvood

2021-12-06 18:36 UTC, FlyLikeSoarin requested changes
Очень чистый код. Хорошо, что ты вынес функции из тела класса. Есть всего один общий недочёт - то что у тебя capacity - не capacity. Очень странное решение - подумай почему это плохо, в этой задаче можно не менять.

2021-12-06 18:36 UTC, FlyLikeSoarin commented on Vsevolod_Kaspirovich/task_string/string.h
> +  if (length_ == 12) {
;)

2021-12-06 18:36 UTC, FlyLikeSoarin commented on Vsevolod_Kaspirovich/task_string/string.h
> +  char* tmp = new char[str.length_ + 1];
Здесь не нужна дополнительная аллокация

2021-12-06 18:36 UTC, FlyLikeSoarin commented on Vsevolod_Kaspirovich/task_string/string.h
> +  while (search_pointer <= &back() &&
Тут получается очень грустная ассимптотика, хуже чем если бы ты сам написал, поэтому тут надо написать самому или подругому подходить к использованию библиотечных функций.

2021-12-12 15:22 UTC, vsvood commented on Vsevolod_Kaspirovich/task_string/string.h
> +  char* tmp = new char[str.length_ + 1];
Не вовремя вспомнил, что strcat неадекватно работает с пересекающимися строками и написал обёртку. Забыл что работаю с контейнером, который гарантирует непересечение.

2021-12-18 19:26 UTC, merged