Completed string
FlyLikeSoarin/atp-cpp-semester-1 pull request #36
Opened 2021-11-11 21:08 UTC by tsmax2004

2021-12-04 13:49 UTC, FlyLikeSoarin requested changes

2021-12-04 13:49 UTC, FlyLikeSoarin commented on MaksimTsoy/string.h
> +    memset(str, c, n);
Жирный плюс за null-terminator, но тут ты его забыл добавить.

2021-12-04 13:49 UTC, FlyLikeSoarin commented on MaksimTsoy/string.h
> +    for (size_t i = len - substr.len; i > 0; --i) {
Чтобы избавиться от копипасты можно использовать do while

2021-12-04 13:49 UTC, FlyLikeSoarin commented on MaksimTsoy/string.h
> +    if (string.size > size)
Здесь было бы логичнее проверять string.len + 1 > size. И выделять set_memory(len + 1).  Твоя строка, например, вполне может иметь size  на порядок больше len (ибо у тебя не освобождается память на pop_back)

2021-12-04 13:49 UTC, FlyLikeSoarin commented on MaksimTsoy/string.h
> +    if (len + string.len >= size - 1)
А что если String("a") + String("a" * 100000)?

2021-12-04 14:22 UTC, tsmax2004 commented on MaksimTsoy/string.h
> +    if (len + string.len >= size - 1)
А что не так тут?

2021-12-04 14:36 UTC, tsmax2004 commented
а я правильно сделал, что поправил код, переместил файл в созданную папку (забыл об этом в самом начале) и закоммитил?

2021-12-13 19:58 UTC, FlyLikeSoarin commented on MaksimTsoy/string.h
> +    if (string.size > size)
Это не исправлено

2021-12-13 22:35 UTC, merged