I passed this task at contest at thursday, but forgot to push it. haha
FlyLikeSoarin/atp-cpp-semester-1 pull request #39
Opened 2021-11-14 21:13 UTC by funtalex

2021-11-14 21:16 UTC, funtalex commented
Что лучше: делать допконструкторы из char в String, не используя explicit, или перегружать операторы по десять раз? дилемма.....

2021-12-06 19:42 UTC, FlyLikeSoarin requested changes
Уделяй больше внимания чистым строкам. Это не влияет на работу кода, но когда, например, перед и после каждой функции есть чистая строка читать код легче.

2021-12-06 19:42 UTC, FlyLikeSoarin commented on Alexey_Sergeechev/String/string.h
> +  String(size_t n, char c) : size(n), str(new char[n]), capacity(n) { //Can I use size instead n?
Да, тут можно использовать size вместо n. Более того, ты делаешь это в методах выше и ниже.

2021-12-06 19:42 UTC, FlyLikeSoarin commented on Alexey_Sergeechev/String/string.h
> +    if (4 * size <= capacity) {
За "сжатие" строки большой плюс.

2021-12-06 19:42 UTC, FlyLikeSoarin commented on Alexey_Sergeechev/String/string.h
> +    (*this).push_back(c);
А зачем здесь `(*this).`?

2021-12-06 19:42 UTC, FlyLikeSoarin commented on Alexey_Sergeechev/String/string.h
> +      capacity += s.capacity;
Capacity же в этом случае не меняется. Так можно словить segfault

2021-12-06 19:42 UTC, FlyLikeSoarin commented on Alexey_Sergeechev/String/string.h
> +        if (str[i + j] != substr[j]) {
Практически та же функция что и выше. Нужно вынести в общую функцию с флагом is_reversed.

2021-12-06 19:42 UTC, FlyLikeSoarin commented on Alexey_Sergeechev/String/string.h
> +    memcpy(copy.str, str + start, count);
Если start + count больше длины строки -  segfault

2021-12-19 13:55 UTC, FlyLikeSoarin requested changes

2021-12-19 13:55 UTC, FlyLikeSoarin commented on Alexey_Sergeechev/String/string.h
> +    }
Но ведь ты просто загнал 2 функции в одну. Копипаста никуда не делать, у тебя 2 практически идентичных цикла. Хотя бы просто засунь 3 тернирника во внешний цикл для 2 случаем, ибо они больше ничем не отличаются.

2021-12-21 11:57 UTC, merged