Add String Task
FlyLikeSoarin/atp-cpp-semester-1 pull request #43
Opened 2021-11-17 15:08 UTC by Supyness

57184126

2021-12-07 00:21 UTC, FlyLikeSoarin requested changes
Уделяй больше внимания чистым строкам. Это не влияет на работу кода, но когда, например, перед и после каждой функции есть чистая строка читать код легче.

Также я бы не советовал использовать побитовые сдвиги как заменитель умножения на 2. 1) Скорее всего компилятор сам умеет применять такие оптимизации. 2) Код становится менее читаемым.

2021-12-07 00:21 UTC, FlyLikeSoarin commented on Sklyarenko-Evgeny/String_Task/String.cpp
> +    str[capacity] = '\0';
Учитывать null терминатор в длине строки не совсем корректно.

2021-12-07 00:21 UTC, FlyLikeSoarin commented on Sklyarenko-Evgeny/String_Task/String.cpp
> +    else {
По кодстайлу else должен быть на той же строке что и `}`, но тут он вообще не нужен, поскольку if заканчивается return'ом

2021-12-07 00:21 UTC, FlyLikeSoarin commented on Sklyarenko-Evgeny/String_Task/String.cpp
> +    delete[] str;
Тут тоже лишняя аллокация

2021-12-19 14:59 UTC, Supyness commented on Sklyarenko-Evgeny/String_Task/String.cpp
> +        if (c == nullptr) return length();
Он точно не ложный, проверял несколько раз, без него не работает.

2021-12-19 15:03 UTC, Supyness commented on Sklyarenko-Evgeny/String_Task/String.cpp
> +    delete[] str;
А разве не возникнут проблемы с size. Я пытался делать без memcpy (циклом и просто приравниванием), и это либо не заходило по времени, либо просто был WA, да и сам мещирин говорил делать через memcpy

2021-12-19 15:06 UTC, Supyness commented on Sklyarenko-Evgeny/String_Task/String.cpp
> + private:
Исправил.

2021-12-19 15:08 UTC, Supyness commented on Sklyarenko-Evgeny/String_Task/String.cpp
> +    str = new char[size];
Так тут не работает, выдает RE. Вообще не очень понимаю, как должно просто работает приравнивание строки, потому что кажется, что это неправильно работает в связи с изменением размера строки. Везде где убирал memcpy сразу выдавало RE, даже когда обрабатывал правильную отчистку памяти (Мещерин рекламировал memcpy на лекциях)

2021-12-19 15:09 UTC, Supyness commented on Sklyarenko-Evgeny/String_Task/String.cpp
> +  void clear_memory() {
Исправил.

2021-12-19 15:09 UTC, Supyness commented on Sklyarenko-Evgeny/String_Task/String.cpp
> +        if (c == nullptr) return length();
Ниже в цикле обновляется c, поэтому кажется, что тут все правильно с if

2021-12-19 15:09 UTC, Supyness commented on Sklyarenko-Evgeny/String_Task/String.cpp
> +    else {
Исправил.

2021-12-19 16:12 UTC, FlyLikeSoarin commented on Sklyarenko-Evgeny/String_Task/String.cpp
> +    str = new char[size];
Ты тут приравниваешь ссылку на область в памяти.Тут нужно написать str = tmp; и всё, после этого ретурн. Тут ты просто перегоняешь данные из одного места в другое точно такое-же

2021-12-19 16:14 UTC, FlyLikeSoarin commented on Sklyarenko-Evgeny/String_Task/String.cpp
> +    delete[] str;
А зачем делать без memcpy? Тут нужно было просто нужно удалить
```
    str = new char[size];
    capacity = strol;
    memcpy(str, tmp, strol);
    delete[] tmp;
```
и заменить на str=tmp;

2021-12-19 17:33 UTC, Supyness commented on Sklyarenko-Evgeny/String_Task/String.cpp
> +      str = new char[size << 1];
Исправил, и правда работает.

2021-12-19 17:33 UTC, Supyness commented on Sklyarenko-Evgeny/String_Task/String.cpp
> +    str = new char[size];
Также исправил.

2021-12-19 17:34 UTC, Supyness commented on Sklyarenko-Evgeny/String_Task/String.cpp
> +    delete[] str;
Тоже исправил, даже время упало на 40мс.

2021-12-21 15:48 UTC, merged