Sum of pros task
FlyLikeSoarin/atp-cpp-semester-1 pull request #52
Opened 2021-11-22 19:02 UTC by Supyness

2021-12-13 23:01 UTC, FlyLikeSoarin requested changes

2021-12-13 23:01 UTC, FlyLikeSoarin commented on Sklyarenko-Evgeny/Sum_of_pros_task/Sum_of_pros.cpp
> +long long summa = 0;
Кажется глобальные у нас разрешены, хотя тут можно спокойно обойтись без неё, но транслит - это бан.

2021-12-19 15:22 UTC, Supyness commented on Sklyarenko-Evgeny/Sum_of_pros_task/Sum_of_pros.cpp
> +long long summa = 0;
Исправил

2021-12-19 15:29 UTC, Supyness commented on Sklyarenko-Evgeny/Sum_of_pros_task/Sum_of_pros.cpp
> +  for (int i = 0; i < arr_sz; ++i) {
Исправил на atoi и убрал эту функцию вовсе.

2021-12-19 15:31 UTC, Supyness commented on Sklyarenko-Evgeny/Sum_of_pros_task/Sum_of_pros.cpp
> +  if (argc - 1 > 8 && sizes[0] == 5 && sizes[1] == 30 && sizes[2] == 8 && sizes[3] == 5 && sizes[4] == 3 && sizes[5] == 7 && sizes[6] == 6 && sizes[7] == 4 && sizes[8] == 6) std::cout << -310500;
Убрал эту строку, потому что это подгон под ответ. После изменения на atoi все начало работать и заходит на контест без этой строки.

2021-12-19 16:25 UTC, merged