Completed сумма произведений
FlyLikeSoarin/atp-cpp-semester-1 pull request #53
Opened 2021-11-23 14:59 UTC by Annarrchy

2021-12-13 23:08 UTC, FlyLikeSoarin requested changes

2021-12-13 23:08 UTC, FlyLikeSoarin commented on Anna-Efimova/task_4_SumOfProduction/SumOfProduct.cpp
> +﻿// SumOfProduct.cpp : Этот файл содержит функцию "main". Здесь начинается и заканчивается выполнение программы.
Это точно нужный файл?

2021-12-14 17:19 UTC, Annarrchy commented on Anna-Efimova/task_4_SumOfProduction/SumOfProduct.cpp
> +﻿// SumOfProduct.cpp : Этот файл содержит функцию "main". Здесь начинается и заканчивается выполнение программы.
Нет, видимо, случайно получилось, сейчас загрузила нужный, Вам виден новый коммит?

2021-12-15 11:53 UTC, FlyLikeSoarin requested changes

2021-12-15 11:53 UTC, FlyLikeSoarin commented on Anna-Efimova/task_4_SumOfProduction/SumOfProduct.cpp
> +	if (a > b)
Тут лучше использовать тернарный оператор, По кодстайлу у  else тело всегда должно быть в фигурных скобках

2021-12-15 11:53 UTC, FlyLikeSoarin commented on Anna-Efimova/task_4_SumOfProduction/SumOfProduct.cpp
> +	if (a > b)
Тут лучше использовать тернаный оператор, по кодстайлу тут у if и else тело должно находиться в фигурных скобках и получается очень громоздко

2021-12-15 11:54 UTC, FlyLikeSoarin commented on Anna-Efimova/task_4_SumOfProduction/SumOfProduct.cpp
> +﻿// SumOfProduct.cpp : Этот файл содержит функцию "main". Здесь начинается и заканчивается выполнение программы.
Да, теперь всё хорошо

2021-12-19 15:37 UTC, merged