Completed BigInteger
FlyLikeSoarin/atp-cpp-semester-1 pull request #55
Opened 2021-11-25 20:45 UTC by tsmax2004

2021-12-15 16:15 UTC, FlyLikeSoarin requested changes

2021-12-15 16:15 UTC, FlyLikeSoarin commented on MaksimTsoy/task_biginteger/biginteger.h
> +    return ((*this < 0) ? -*this : *this);
Тут вместо сравнения можно поставить isMinus

2021-12-15 16:15 UTC, FlyLikeSoarin commented on MaksimTsoy/task_biginteger/biginteger.h
> +  void short_rational() {
Названием void метода должен быть глагол

2021-12-15 16:15 UTC, FlyLikeSoarin commented on MaksimTsoy/task_biginteger/biginteger.h
> +      else
в if else тело должно быть в фигурных скобках

2021-12-15 16:15 UTC, FlyLikeSoarin commented on MaksimTsoy/task_biginteger/biginteger.h
> +          number.push_back(0);
Тут можно использовать number.resize()

2021-12-15 16:15 UTC, FlyLikeSoarin commented on MaksimTsoy/task_biginteger/biginteger.h
> +    // what return if rational overflow of double ???
Числа с плавающей точкой имеют специальное значение - INF (-INF)

https://en.cppreference.com/w/cpp/types/numeric_limits/infinity

2021-12-18 17:53 UTC, FlyLikeSoarin commented on MaksimTsoy/task_biginteger/biginteger.h
> +    return (isMinus ? !is_not_greater_than(x) : is_not_greater_than(x));
Поправь ещё это. Всё остальное норм.

2021-12-18 18:00 UTC, tsmax2004 commented on MaksimTsoy/task_biginteger/biginteger.h
> +    return (isMinus ? !is_not_greater_than(x) : is_not_greater_than(x));
Оно же уже верно работает

2021-12-18 19:47 UTC, FlyLikeSoarin commented on MaksimTsoy/task_biginteger/biginteger.h
> +    return (isMinus ? !is_not_greater_than(x) : is_not_greater_than(x));
А сорри, не заметил. Засчитано:)

2021-12-18 19:47 UTC, merged