Completed BigInteger_Task
FlyLikeSoarin/atp-cpp-semester-1 pull request #56
Opened 2021-11-27 12:48 UTC by Supyness

2021-12-18 00:54 UTC, FlyLikeSoarin requested changes

2021-12-18 00:54 UTC, FlyLikeSoarin commented on Sklyarenko-Evgeny/BigInteger/BigInteger_Task.cpp
> +  BigInteger &operator+=(const BigInteger &num) {
Подумай как можно переписать эту функцию, она должна занимать максимум 50 строк, а лучше сильно меньше. Хотя бы то что случаи с двумя отрицательными и двумя положительными числами особо ничем не отличаются.

2021-12-18 00:54 UTC, FlyLikeSoarin commented on Sklyarenko-Evgeny/BigInteger/BigInteger_Task.cpp
> +  BigInteger &operator+=(const BigInteger &num) {
Если не понимаешь как переделать - можешь написать мне, но функция должна уложиться в 50, а лучше 30 строк, причём без особых ухищрений

2021-12-18 00:54 UTC, FlyLikeSoarin commented on Sklyarenko-Evgeny/BigInteger/BigInteger_Task.cpp
> +  BigInteger &operator-=(const BigInteger &num) {
Это копипаста предыдущего метода. Тут вообще почти ничего быть не должно.

2021-12-18 00:54 UTC, FlyLikeSoarin commented on Sklyarenko-Evgeny/BigInteger/BigInteger_Task.cpp
> +  void irreducible() {
Название должно отражать действие

2021-12-19 15:34 UTC, Supyness commented on Sklyarenko-Evgeny/BigInteger/BigInteger_Task.cpp
> + private:
Исправил.

2021-12-19 15:34 UTC, Supyness commented on Sklyarenko-Evgeny/BigInteger/BigInteger_Task.cpp
> +    while (this->arr.size() > 1 && this->arr.back() == 0) {
Исправил везде.

2021-12-19 15:36 UTC, Supyness commented on Sklyarenko-Evgeny/BigInteger/BigInteger_Task.cpp
> +  void change_row() {
Оказалось, что эта функция вообще нигде не использовалась. Убрал.

2021-12-19 15:37 UTC, Supyness commented on Sklyarenko-Evgeny/BigInteger/BigInteger_Task.cpp
> +    tmp.is_negative = (this->is_negative + 1) % 2;
Исправил!

2021-12-19 15:38 UTC, Supyness commented on Sklyarenko-Evgeny/BigInteger/BigInteger_Task.cpp
> +    else if (this->arr.size() > num.arr.size()) return true;
Исправил.

2021-12-19 15:38 UTC, Supyness commented on Sklyarenko-Evgeny/BigInteger/BigInteger_Task.cpp
> +        if (this->arr[i] > num.arr[i]) return true;
Исправил.

2021-12-19 15:47 UTC, Supyness commented on Sklyarenko-Evgeny/BigInteger/BigInteger_Task.cpp
> +  bool operator>(const BigInteger &num) const {
Исправил, теперь функция вышла в 4 строки.

2021-12-19 15:47 UTC, Supyness commented on Sklyarenko-Evgeny/BigInteger/BigInteger_Task.cpp
> +  BigInteger &operator+=(const BigInteger &num) {
Переписал, но вышло все равно чуть больше 50 строк...

2021-12-19 15:47 UTC, Supyness commented on Sklyarenko-Evgeny/BigInteger/BigInteger_Task.cpp
> +  BigInteger &operator-=(const BigInteger &num) {
Также исправил.

2021-12-19 15:49 UTC, Supyness commented on Sklyarenko-Evgeny/BigInteger/BigInteger_Task.cpp
> +  void irreducible() {
Исправил на глагол reduce.

2021-12-19 16:34 UTC, FlyLikeSoarin requested changes

2021-12-19 16:34 UTC, FlyLikeSoarin commented on Sklyarenko-Evgeny/BigInteger/BigInteger_Task.cpp
> +  bool abs_compare_lower(const BigInteger &num) const {
Это нужно поправить

2021-12-19 16:34 UTC, FlyLikeSoarin commented on Sklyarenko-Evgeny/BigInteger/BigInteger_Task.cpp
> +  }*/
Всегда убирай закомментированный код из коммитом, для того чтобы посмотреть как было раньше есть гит

2021-12-19 16:34 UTC, FlyLikeSoarin commented on Sklyarenko-Evgeny/BigInteger/BigInteger_Task.cpp
> +  BigInteger &operator+=(const BigInteger &num) {
Уже лучше. Посмотри ещё на операторы += и -=, они очень похожи и можно сделать так, чтобы код не повторялся

2021-12-19 16:34 UTC, FlyLikeSoarin commented on Sklyarenko-Evgeny/BigInteger/BigInteger_Task.cpp
> +              counter[j] += base;
А что делает эта функция?

2021-12-19 17:17 UTC, Supyness commented on Sklyarenko-Evgeny/BigInteger/BigInteger_Task.cpp
> +              counter[j] += base;
Исправил название, теперь должно быть понятнее.

2021-12-19 17:17 UTC, Supyness commented on Sklyarenko-Evgeny/BigInteger/BigInteger_Task.cpp
> +  }*/
Убрал!

2021-12-19 17:28 UTC, Supyness commented on Sklyarenko-Evgeny/BigInteger/BigInteger_Task.cpp
> +  BigInteger &operator+=(const BigInteger &num) {
Я, наверное, понимаю, что надо разность выразить через сумму, но с константным объектом num я не смогу это сделать. Тогда получается придется думать над беззнаковой функцией суммы и разности и переписывать код.

2021-12-19 17:38 UTC, Supyness commented on Sklyarenko-Evgeny/BigInteger/BigInteger_Task.cpp
> +  bool abs_compare_lower(const BigInteger &num) const {
Поправил название.

2021-12-20 07:33 UTC, merged