Complete BigInteger
FlyLikeSoarin/atp-cpp-semester-1 pull request #65
Opened 2021-12-06 19:44 UTC by vsvood

2021-12-18 15:14 UTC, FlyLikeSoarin requested changes

2021-12-18 15:14 UTC, FlyLikeSoarin commented on Vsevolod_Kaspirovich/BigInt/biginteger.h
> +  if (is_negative_ > other.is_negative_) {
Тут не должно быть столько условных операторов. эту функцию можно разбить на 3 основных части: разные знаки, разная длина, одинаковая длина => постарайся уложиться в 3 внешних ифа

2021-12-18 15:14 UTC, FlyLikeSoarin commented on Vsevolod_Kaspirovich/BigInt/biginteger.h
> +  if (is_negative_ > other.is_negative_) {
Ну и применять арифметические операторы к логическим переменным не хорошо

2021-12-18 15:14 UTC, FlyLikeSoarin commented on Vsevolod_Kaspirovich/BigInt/biginteger.h
> +std::string BigInteger::toStringAsFixedPoint(uint64_t precision) const {
Эта функция никак не используется в бигинте, почему она реализована тут? Если это нужно в Rational - реализуй функционал там.

2021-12-18 15:14 UTC, FlyLikeSoarin commented on Vsevolod_Kaspirovich/BigInt/biginteger.h
> +std::string BigInteger::toStringAsFixedPoint(uint64_t precision) const {
И пожалуйста, подумай как делать эту функцию проще, 100 строк - это перебор. Кажется это проблема решается арифметическими операциями, методом toString и взятием подстоки

2021-12-18 15:14 UTC, FlyLikeSoarin commented on Vsevolod_Kaspirovich/BigInt/biginteger.h
> +  void Reduce();
Если у тебя все методы начинаются с маленькой буквы - этот тоже должен

2021-12-21 17:21 UTC, vsvood commented on Vsevolod_Kaspirovich/BigInt/biginteger.h
> +std::string BigInteger::toStringAsFixedPoint(uint64_t precision) const {
Это невозможно. У Rational нет прямого доступа к массиву чисел который является истинным представлением BigInt и это правильно, т.к. Rational должно быть абстрагированно от реализации BigInt. Тут придется или через операторы % и / доставать числа из Bigint в новый вектоор и работать с ним, что является крайним извращением, либо реализовать опрератор для fixed point арифметики, который скорее относится к BigInt , т.к. число с фиксированной точкой ближе к целому чем к рациональному

2021-12-21 17:24 UTC, vsvood commented on Vsevolod_Kaspirovich/BigInt/biginteger.h
> +  void Reduce();
Переименовал

2021-12-21 17:24 UTC, vsvood commented on Vsevolod_Kaspirovich/BigInt/biginteger.h
> +  ////////std::cerr << "+=" << *this << ' ' << other << '\n';
убрал

2021-12-21 17:53 UTC, FlyLikeSoarin commented on Vsevolod_Kaspirovich/BigInt/biginteger.h
> +std::string BigInteger::toStringAsFixedPoint(uint64_t precision) const {
Нет ничего невозможного. Rational можно сделать friend классом, но вообще я говорил про то, что, что просто можно домножить числитель на 10 в необходимой степени, поделить на знаменать и почти всё готово. Я на самом деле даже не очень понимаю, как ты в этой функции это делаешь учитывая, что знаешь ты лишь про 1 бигинт

2021-12-21 20:36 UTC, merged