String
FlyLikeSoarin/atp-cpp-semester-1 pull request #68
Opened 2021-12-07 20:32 UTC by mrnonam88

Это стринга

2021-12-09 11:27 UTC, FlyLikeSoarin requested changes
Много небольших замечаний. Спасибо что оставляешь комментарии, но отступы надо привести в порядок

2021-12-09 11:27 UTC, FlyLikeSoarin commented on George_Kuznetsov/String/string.h
> +class String{
Приватные поля и медоты лучше перенести в конец класса. Всё-таки первое что хочет увидеть человек который смотрит твой код - это публичные поля, которыми ему разрешено пользоваться.

2021-12-09 11:27 UTC, FlyLikeSoarin commented on George_Kuznetsov/String/string.h
> +        //Конструктор от C-style строки
Зачем столько оступов? Это нарушает кодстайл, а люди с маленькими мониторами будут страдать. Чтобы указать где какая секция кода комментариев достаточно

2021-12-09 11:27 UTC, FlyLikeSoarin commented on George_Kuznetsov/String/string.h
> +//                std::cout << size << " --- " << max_size << "\n";
Удали закомментированый код

2021-12-09 11:27 UTC, FlyLikeSoarin commented on George_Kuznetsov/String/string.h
> +                std::swap(size, swap_string.size);
Забыл max_size

2021-12-09 11:27 UTC, FlyLikeSoarin commented on George_Kuznetsov/String/string.h
> +                return size <= 0;
А почему <=?

2021-12-09 11:27 UTC, FlyLikeSoarin commented on George_Kuznetsov/String/string.h
> +                delete[] str;
А зачем удалять str, если он по умолчанию нуллптр, а это конструктор.

2021-12-09 11:27 UTC, FlyLikeSoarin commented on George_Kuznetsov/String/string.h
> +            String(const char* input){
Используй списки инициализации

2021-12-09 11:27 UTC, FlyLikeSoarin commented on George_Kuznetsov/String/string.h
> +                    if (str[i] == substring.str[0]){
Кажется внешний иф не нужен, если его удалить ничего не изменится

2021-12-09 11:27 UTC, FlyLikeSoarin commented on George_Kuznetsov/String/string.h
> +                for (size_t i = size - substring.size + 1; i > 0 ; --i) {
Код, кроме порядка обхода во внешнем цикле, идентичен методу find. Вынеси в отдельную функцию

2021-12-09 11:27 UTC, FlyLikeSoarin commented on George_Kuznetsov/String/string.h
> +            String substr(size_t start, size_t count){
Неконстантная версия метода ничего не меняет в состоянии класса и асболютно идентична константной. Этот метод нужно удалить

2021-12-09 11:27 UTC, FlyLikeSoarin commented on George_Kuznetsov/String/string.h
> +            String& operator=(const char input[]){
А что если строка была не пустой

2021-12-09 16:17 UTC, mrnonam88 commented
Ок, сейчас все будет

Отправлено с iPhone

> 9 дек. 2021 г., в 14:27, Eugene Vihrev ***@***.***> написал(а):
> 
> ﻿
> @FlyLikeSoarin requested changes on this pull request.
> 
> Много небольших замечаний. Спасибо что оставляешь комментарии, но отступы надо привести в порядок
> 
> In George_Kuznetsov/String/string.h:
> 
> > @@ -0,0 +1,362 @@
> +#include <iostream>
> +#include <cstring>
> +#include <algorithm>
> +
> +
> +class String{
> Приватные поля и медоты лучше перенести в конец класса. Всё-таки первое что хочет увидеть человек который смотрит твой код - это публичные поля, которыми ему разрешено пользоваться.
> 
> In George_Kuznetsov/String/string.h:
> 
> > +
> +
> +class String{
> +private:
> +    char* str = nullptr;
> +    size_t size = 0;
> +    size_t max_size = 1;
> +
> +public:
> +
> +    //Конструкторы:
> +
> +        //Конструктор по умолчанию
> +            String() = default;
> +
> +        //Конструктор от C-style строки
> Зачем столько оступов? Это нарушает кодстайл, а люди с маленькими мониторами будут страдать. Чтобы указать где какая секция кода комментариев достаточно
> 
> In George_Kuznetsov/String/string.h:
> 
> > +
> +    //Конструкторы:
> +
> +        //Конструктор по умолчанию
> +            String() = default;
> +
> +        //Конструктор от C-style строки
> +            String(const char* input){
> +                size = strlen(input);
> +                delete[] str;
> +                while (max_size < size){
> +                    max_size *= 2;
> +                }
> +                str = new char[max_size];
> +                memcpy(str, input, size);
> +//                std::cout << size << " --- " << max_size << "\n";
> Удали закомментированый код
> 
> In George_Kuznetsov/String/string.h:
> 
> > +
> +        //Конструктор копирования
> +            String(const String& cpy_string){
> +                str = new char [cpy_string.size];
> +                size = cpy_string.size;
> +                max_size = cpy_string.max_size;
> +                memcpy(str, cpy_string.str, cpy_string.size);
> +            }
> +//------------------------------------------------------------------------------------------------------
> +
> +    //Методы
> +
> +        //Функция перестановки строк
> +            void swap(String& swap_string){
> +                std::swap(str, swap_string.str);
> +                std::swap(size, swap_string.size);
> Забыл max_size
> 
> In George_Kuznetsov/String/string.h:
> 
> > +            }
> +            [[nodiscard]] const char& front() const{
> +                return str[0];
> +            }
> +
> +        //Метод back() - возвращает ссылку на последний элемент
> +            [[nodiscard]] char& back(){
> +                return str[size - 1];
> +            }
> +            [[nodiscard]] const char& back() const{
> +                return str[size - 1];
> +            }
> +
> +        //Метод empty() - проверяет пустая ли строка
> +            [[nodiscard]] bool empty() const{
> +                return size <= 0;
> А почему <=?
> 
> In George_Kuznetsov/String/string.h:
> 
> > +private:
> +    char* str = nullptr;
> +    size_t size = 0;
> +    size_t max_size = 1;
> +
> +public:
> +
> +    //Конструкторы:
> +
> +        //Конструктор по умолчанию
> +            String() = default;
> +
> +        //Конструктор от C-style строки
> +            String(const char* input){
> +                size = strlen(input);
> +                delete[] str;
> А зачем удалять str, если он по умолчанию нуллптр, а это конструктор.
> 
> In George_Kuznetsov/String/string.h:
> 
> > +
> +class String{
> +private:
> +    char* str = nullptr;
> +    size_t size = 0;
> +    size_t max_size = 1;
> +
> +public:
> +
> +    //Конструкторы:
> +
> +        //Конструктор по умолчанию
> +            String() = default;
> +
> +        //Конструктор от C-style строки
> +            String(const char* input){
> Используй списки инициализации
> 
> In George_Kuznetsov/String/string.h:
> 
> > +            }
> +
> +        //Метод clear() - очищает строку
> +            void clear(){
> +                delete[] str;
> +                str = nullptr;
> +                size = 0;
> +                max_size = 1;
> +            }
> +
> +        //Метод find() - ищет самую левую подстроку
> +            size_t find(const String&  substring) const{
> +                bool flag = false;
> +                for (size_t i = 0; i <= size - substring.size; ++i) {
> +        //                    std::cout << i << " ... " << str[i] << " - " << substring.str[0] << "\n";
> +                    if (str[i] == substring.str[0]){
> Кажется внешний иф не нужен, если его удалить ничего не изменится
> 
> In George_Kuznetsov/String/string.h:
> 
> > +                                flag = false;
> +                                break;
> +                            }
> +                        }
> +                        if (flag){
> +                            return i;
> +                        }
> +                    }
> +                }
> +                return size;
> +            }
> +
> +        //Метод rfind() - ищет самую правую подстроку
> +            size_t rfind(const String& substring) const {
> +                bool flag = false;
> +                for (size_t i = size - substring.size + 1; i > 0 ; --i) {
> Код, кроме порядка обхода во внешнем цикле, идентичен методу find. Вынеси в отдельную функцию
> 
> In George_Kuznetsov/String/string.h:
> 
> > +                            if (str[i + j] != substring.str[j]){
> +                                flag = false;
> +                                break;
> +                            }
> +                        }
> +                        if (flag){
> +                            return i;
> +                        }
> +                    }
> +            }
> +
> +            return size;
> +        }
> +
> +        //Метод subtsr() - возвращает подстроку
> +            String substr(size_t start, size_t count){
> Неконстантная версия метода ничего не меняет в состоянии класса и асболютно идентична константной. Этот метод нужно удалить
> 
> In George_Kuznetsov/String/string.h:
> 
> > +            //строка == 'символ'
> +                friend bool operator==(const String& string, char symbol);
> +            //'символ' == строка
> +                friend bool operator==(char symbol, const String& string);
> +            //"слово" == 'символ'
> +                friend bool operator==(const char* word, const String& string);
> +
> +        //Оператор присваивания
> +            String& operator=(const String& cpy_string){
> +                if (str != cpy_string.str){
> +                    String copy_string = cpy_string;
> +                    swap(copy_string);
> +                }
> +                return *this;
> +            }
> +            String& operator=(const char input[]){
> А что если строка была не пустой
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.

2021-12-18 19:32 UTC, FlyLikeSoarin commented
Изменения нужно внести в файл string.h, закоммитить их и запушить

2021-12-19 15:51 UTC, FlyLikeSoarin requested changes

2021-12-19 15:51 UTC, FlyLikeSoarin commented on George_Kuznetsov/String/string.h
> +  }
![Screenshot from 2021-12-19 18-49-41](https://user-images.githubusercontent.com/30130196/146681366-f9401821-1f54-4a40-8eb8-5e57116eb81a.png)

Копипаста. Нужно вынести во внешнюю функцию или любым другим способом убрать повторение кода.

2021-12-21 16:06 UTC, merged