Matrix
FlyLikeSoarin/atp-cpp-semester-1 pull request #78
Opened 2021-12-16 21:14 UTC by Supyness

2021-12-18 17:18 UTC, FlyLikeSoarin requested changes

2021-12-18 17:18 UTC, FlyLikeSoarin commented on Sklyarenko-Evgeny/Matrix/matrix.cpp
> +//    std::cerr << 8 << std::endl;
Удали комментарии из кода

2021-12-18 17:18 UTC, FlyLikeSoarin commented on Sklyarenko-Evgeny/Matrix/matrix.cpp
> + private:
Сначало публичные методы и поля

2021-12-19 15:13 UTC, Supyness commented on Sklyarenko-Evgeny/Matrix/matrix.cpp
> + private:
Исправил.

2021-12-19 15:14 UTC, Supyness commented on Sklyarenko-Evgeny/Matrix/matrix.cpp
> +//    std::cerr << 8 << std::endl;
Убрал.

2021-12-19 16:15 UTC, merged